#  Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
#  the License. A copy of the License is located at
#      http://aws.amazon.com/apache2.0/
#  or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and
#  limitations under the License.

AWSTemplateFormatVersion: "2010-09-09"
Description: Deployment for OCS Audience SSO (Single Sign ON)
Parameters:
  Environment:
    Type: String
    '''  
    AllowedValues:
      - dev
      - stage
      - prod

    '''
  ProjectName:
    Description: Mi primer proyecto
    Type: String
   # Default: audience-sso-dev
  S3Bucket:
    Description: bucket_prueba
    Type: String
   # Default: core-deployment-bucket-key-roles-artifactbucket-k91z60qmptt8

  ''' 
  CMKARN:
    Description: ARN of the KMS CMK creates in Devops account
    Type: String
    Default: arn:aws:kms:eu-west-1:112555760202:key/759c4789-8077-4fef-9681-e0ff306b96cc

  '''
  
  GitHubRepoName:
    Description: The repo we're building from
    Type: String
    Default: ddna-audience-sso
  GitHubBranch:
    Description: The branch we're building from
    Type: String
    Default: dev


Mappings:
  EnvironmentsAndRoles:
    dev:
      PipelineRole: arn:aws:iam::328502120762:role/DevopsAccCodePipelineCloudFormationRole
      CfnDeploy: arn:aws:iam::328502120762:role/DevopsAcctCldfrmtnDeployerRole
    stage:
      PipelineRole: arn:aws:iam::879022424377:role/DevopsAccCodePipelineCloudFormationRole
      CfnDeploy: arn:aws:iam::879022424377:role/DevopsAcctCldfrmtnDeployerRole
    prod:
      PipelineRole: arn:aws:iam::789398071196:role/DevopsAccCodePipelineCloudFormationRole
      CfnDeploy: arn:aws:iam::789398071196:role/DevopsAcctCldfrmtnDeployerRole


Resources:
  AppPipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: "{{resolve:secretsmanager:devops/github:SecretString:WebhookSecret}}"
      Filters:
        -
          JsonPath: "$.ref"
          MatchEquals: !Sub "refs/heads/${GitHubBranch}"
      TargetPipeline: !Ref Pipeline
      TargetAction: GetSource
      Name: !Sub ${AWS::StackName}
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true

  EcrSFSCExporterRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub "audience-sso-sfsc-exporter-${Environment}"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::328502120762:root
                - arn:aws:iam::789398071196:root
                - arn:aws:iam::879022424377:root
                - arn:aws:iam::112555760202:root
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"

  EcrSFMCSFTPImporterRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub "audience-sso-sfmc-sftp-importer-${Environment}"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::328502120762:root
                - arn:aws:iam::789398071196:root
                - arn:aws:iam::879022424377:root
                - arn:aws:iam::112555760202:root
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"

  EcrSCVDeleterRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub "audience-sso-scv-deleter-${Environment}"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::328502120762:root
                - arn:aws:iam::789398071196:root
                - arn:aws:iam::879022424377:root
                - arn:aws:iam::112555760202:root
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"

  EcrSCVLegacySubscriptionsUpdaterRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub "audience-sso-scv-legacy-subscriptions-updater-${Environment}"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::328502120762:root
                - arn:aws:iam::789398071196:root
                - arn:aws:iam::879022424377:root
                - arn:aws:iam::112555760202:root
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"

  EcrSCVSharedToRedshiftMtrViewsRefresherRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub "audience-sso-scv-redshiftrefresher-${Environment}"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::328502120762:root
                - arn:aws:iam::789398071196:root
                - arn:aws:iam::879022424377:root
                - arn:aws:iam::112555760202:root
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"

  EcrSCVSharedToSFMCMtrViewsRefresherRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub "audience-sso-scv-sfmcrefresher-${Environment}"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::328502120762:root
                - arn:aws:iam::789398071196:root
                - arn:aws:iam::879022424377:root
                - arn:aws:iam::112555760202:root
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::112555760202:role/shared-CodePipelineRole
      Name: !Ref AWS::StackName
      ArtifactStore:
       Type: S3
       Location: !Ref S3Bucket
       EncryptionKey:
         Id: !Ref CMKARN
         Type: KMS

      Stages:
        - Name: Source
          Actions:
            - Name: GetSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: OlympicChannelTechOps
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubBranch
                OAuthToken: "{{resolve:secretsmanager:devops/github:SecretString:Token}}"
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: TemplateSource
              RunOrder: 1
        - Name: Build-Source
          Actions:
            - Name: BuildSource
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: TemplateSource
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref BuildStuff
                PrimarySource: TemplateSource
              RunOrder: 1
        - Name: Make-Change-Set
          Actions:
            - Name: MakeChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: !Ref ProjectName
                ActionMode: CHANGE_SET_REPLACE
                StackName: !Ref ProjectName
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: BuildOutput::package.yaml
                TemplateConfiguration: !Sub TemplateSource::config/${Environment}/${AWS::Region}.json
                RoleArn:
                  !FindInMap [EnvironmentsAndRoles, !Ref Environment, CfnDeploy ]
              InputArtifacts:
                - Name: BuildOutput
                - Name: TemplateSource
              RunOrder: 1
              RoleArn:
                  !FindInMap [EnvironmentsAndRoles, !Ref Environment, PipelineRole ]
        - Name: Deploy
          Actions:
            - Name: API
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: !Ref ProjectName
                ActionMode: CHANGE_SET_EXECUTE
                StackName: !Ref ProjectName
                RoleArn:
                  !FindInMap [EnvironmentsAndRoles, !Ref Environment, CfnDeploy ]
              RoleArn:
                !FindInMap [EnvironmentsAndRoles, !Ref Environment, PipelineRole ]

  BuildStuff:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Description: !Ref ProjectName
      EncryptionKey: !Ref CMKARN
      ServiceRole: arn:aws:iam::112555760202:role/shared-CodeBuildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        PrivilegedMode: True
        EnvironmentVariables:
          - Name: DOCKERHUB_TOKEN
            Value: "/MGMT/dockerhub/access_token"
            Type: PARAMETER_STORE
          - Name: DOCKERHUB_USER
            Value: "ocsdatamanagement"
          - Name: S3Bucket
            Value: !Ref S3Bucket
          - Name: S3BucketUsEast2
            Value: core-deployment-us-east-2-bucket-artifactbucket-ka5w8dm7s2s2
          - Name: KMSKey
            Value: !Ref CMKARN
          - Name: STACKNAME
            Value: !Ref ProjectName
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_REGION
            Value: !Ref AWS::Region
          - Name: CODEARTIFACT_DOMAIN
            Value: ocsddna
          - Name: CODEARTIFACT_REPO
            Value: ddna-mgmt
          - Name: SFSC_EXPORTER_REPOSITORY_URI
            Value: !Join
              - ""
              - - !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/"
                - !Ref EcrSFSCExporterRepository
          - Name: SFMC_SFTP_IMPORTER_REPOSITORY_URI
            Value: !Join
              - ""
              - - !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/"
                - !Ref EcrSFMCSFTPImporterRepository
          - Name: SCV_DELETER_REPOSITORY_URI
            Value: !Join
              - ""
              - - !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/"
                - !Ref EcrSCVDeleterRepository
          - Name: SCV_LEGACY_SUBSCRIPTIONS_UPDATER_REPOSITORY_URI
            Value: !Join
              - ""
              - - !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/"
                - !Ref EcrSCVLegacySubscriptionsUpdaterRepository
          - Name: SCV_SHARED_TO_REDSHIFT_MTR_VIEWS_REFRESHER_REPOSITORY_URI
            Value: !Join
              - ""
              - - !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/"
                - !Ref EcrSCVSharedToRedshiftMtrViewsRefresherRepository
          - Name: SCV_SHARED_TO_SFMC_MTR_VIEWS_REFRESHER_REPOSITORY_URI
            Value: !Join
              - ""
              - - !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/"
                - !Ref EcrSCVSharedToSFMCMtrViewsRefresherRepository
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: latest
              commands:
                - ls -R
            pre_build:
              commands:
                - echo "Updating AWSCLI and login into Codeartifact"
                - pip3 install awscli --upgrade --user
                - aws codeartifact login --tool pip --repository ddna-mgmt --domain ocsddna --domain-owner ${AWS_ACCOUNT_ID}
                - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
                - IMAGE_TAG=${COMMIT_HASH:=latest}
                - echo "Logging in to Dockerhub ..."
                - echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USER --password-stdin
                - $(aws ecr get-login --no-include-email)
            build:
              commands:
                - echo "Build started on `date`"
                - echo "Building the Docker image (SFSCExporter)..."
                - pip install -r functions/sfsc_exporter/requirements.txt -t functions/sfsc_exporter/
                - pip install libs/audiencesso -t functions/sfsc_exporter/
                - docker build -t $SFSC_EXPORTER_REPOSITORY_URI:latest functions/sfsc_exporter/
                - docker tag $SFSC_EXPORTER_REPOSITORY_URI:latest $SFSC_EXPORTER_REPOSITORY_URI:$IMAGE_TAG

                - echo "Building the Docker image (SFMCSFTPImporter)..."
                - pip install -r functions/sfmc_sftp_importer/requirements.txt -t functions/sfmc_sftp_importer/
                - pip install libs/audiencesso -t functions/sfmc_sftp_importer/
                - docker build -t $SFMC_SFTP_IMPORTER_REPOSITORY_URI:latest functions/sfmc_sftp_importer/
                - docker tag $SFMC_SFTP_IMPORTER_REPOSITORY_URI:latest $SFMC_SFTP_IMPORTER_REPOSITORY_URI:$IMAGE_TAG

                - echo "Building the Docker image (SCVDeleter)..."
                - pip install -r functions/scv_deleter/requirements.txt -t functions/scv_deleter/
                - pip install libs/audiencesso -t functions/scv_deleter/
                - docker build -t $SCV_DELETER_REPOSITORY_URI:latest functions/scv_deleter/
                - docker tag $SCV_DELETER_REPOSITORY_URI:latest $SCV_DELETER_REPOSITORY_URI:$IMAGE_TAG

                - echo "Building the Docker image (SCVLegacySubscriptionsUpdater)..."
                - pip install -r functions/scv_legacy_subscriptions_updater/requirements.txt -t functions/scv_legacy_subscriptions_updater/
                - pip install libs/audiencesso -t functions/scv_legacy_subscriptions_updater/
                - docker build -t $SCV_LEGACY_SUBSCRIPTIONS_UPDATER_REPOSITORY_URI:latest functions/scv_legacy_subscriptions_updater/
                - docker tag $SCV_LEGACY_SUBSCRIPTIONS_UPDATER_REPOSITORY_URI:latest $SCV_LEGACY_SUBSCRIPTIONS_UPDATER_REPOSITORY_URI:$IMAGE_TAG

                - echo "Building the Docker image (SCVSharedToRedshiftMtrViewsRefresher)..."
                - pip install -r functions/scv_shared_to_redshift_mtr_views_refresher/requirements.txt -t functions/scv_shared_to_redshift_mtr_views_refresher/
                - pip install libs/audiencesso -t functions/scv_shared_to_redshift_mtr_views_refresher/
                - docker build -t $SCV_SHARED_TO_REDSHIFT_MTR_VIEWS_REFRESHER_REPOSITORY_URI:latest functions/scv_shared_to_redshift_mtr_views_refresher/
                - docker tag $SCV_SHARED_TO_REDSHIFT_MTR_VIEWS_REFRESHER_REPOSITORY_URI:latest $SCV_SHARED_TO_REDSHIFT_MTR_VIEWS_REFRESHER_REPOSITORY_URI:$IMAGE_TAG

                - echo "Building the Docker image (SCVSharedToSFMCMtrViewsRefresher)..."
                - pip install -r functions/scv_shared_to_sfmc_mtr_views_refresher/requirements.txt -t functions/scv_shared_to_sfmc_mtr_views_refresher/
                - pip install libs/audiencesso -t functions/scv_shared_to_sfmc_mtr_views_refresher/
                - docker build -t $SCV_SHARED_TO_SFMC_MTR_VIEWS_REFRESHER_REPOSITORY_URI:latest functions/scv_shared_to_sfmc_mtr_views_refresher/
                - docker tag $SCV_SHARED_TO_SFMC_MTR_VIEWS_REFRESHER_REPOSITORY_URI:latest $SCV_SHARED_TO_SFMC_MTR_VIEWS_REFRESHER_REPOSITORY_URI:$IMAGE_TAG

                - echo "Building lambda functions..."
                - pip install -r functions/sanitiser/requirements.txt -t functions/sanitiser/
                - pip install libs/audiencesso -t functions/sanitiser/
                - pip install -r functions/scv_importer/requirements.txt -t functions/scv_importer/
                - pip install libs/audiencesso -t functions/scv_importer/
                - pip install -r functions/scv_ip_importer/requirements.txt -t functions/scv_ip_importer/
                - pip install libs/audiencesso -t functions/scv_ip_importer/
                - pip install -r functions/scv_ip_deduplicator/requirements.txt -t functions/scv_ip_deduplicator/
                - pip install libs/audiencesso -t functions/scv_ip_deduplicator/
                - pip install -r functions/api/requirements.txt -t functions/api/
                - pip install libs/audiencesso -t functions/api/
                - pip install -r functions/api_auth/requirements.txt -t functions/api_auth/
                - pip install libs/audiencesso -t functions/api_auth/
                - pip install -r functions/replay/requirements.txt -t functions/replay/
                - pip install -r functions/fdna_to_scv_importer/requirements.txt -t functions/fdna_to_scv_importer/
                - pip install libs/audiencesso -t functions/fdna_to_scv_importer/
            post_build:
              commands:
                - echo "Build completed on `date`"
                - echo "Pushing the Docker images..."

                - docker push $SFSC_EXPORTER_REPOSITORY_URI:latest
                - docker push $SFSC_EXPORTER_REPOSITORY_URI:$IMAGE_TAG

                - docker push $SFMC_SFTP_IMPORTER_REPOSITORY_URI:latest
                - docker push $SFMC_SFTP_IMPORTER_REPOSITORY_URI:$IMAGE_TAG

                - docker push $SCV_DELETER_REPOSITORY_URI:latest
                - docker push $SCV_DELETER_REPOSITORY_URI:$IMAGE_TAG

                - docker push $SCV_LEGACY_SUBSCRIPTIONS_UPDATER_REPOSITORY_URI:latest
                - docker push $SCV_LEGACY_SUBSCRIPTIONS_UPDATER_REPOSITORY_URI:$IMAGE_TAG

                - docker push $SCV_SHARED_TO_REDSHIFT_MTR_VIEWS_REFRESHER_REPOSITORY_URI:latest
                - docker push $SCV_SHARED_TO_REDSHIFT_MTR_VIEWS_REFRESHER_REPOSITORY_URI:$IMAGE_TAG

                - docker push $SCV_SHARED_TO_SFMC_MTR_VIEWS_REFRESHER_REPOSITORY_URI:latest
                - docker push $SCV_SHARED_TO_SFMC_MTR_VIEWS_REFRESHER_REPOSITORY_URI:$IMAGE_TAG

                - echo "Packaging Cloudformation template"
                - aws cloudformation package --template-file template.yaml --s3-bucket $S3Bucket --s3-prefix ${STACKNAME}/codebuild --output-template-file package.yaml
          artifacts:
            files:
             - package.yaml
            discard-paths: yes
